# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]

# Print numpy version
print(np.__version__)

# Print numpy config
print(np.show_config())

2.3.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuratio

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]

# --- Method 1: Using randint ---
# Generates random integers between 0 and 9
# Shape of the array is (2, 3, 5)
a = np.random.randint(0, 10, size=(2, 3, 5))
print(a)

[[[7 8 0 9 6]
  [2 7 7 2 4]
  [8 1 5 5 5]]

 [[8 9 7 3 9]
  [5 3 6 4 5]
  [6 8 8 0 7]]]


In [4]:
# --- Method 2: Using random ---
# Generates random floating-point numbers between 0 and 1
# Shape of the array is (2, 3, 5)
test = np.random.random(size=(2, 3, 5))
print(test)

[[[0.60858022 0.31906126 0.4079385  0.1451774  0.32303307]
  [0.5815146  0.44584422 0.28106712 0.06790703 0.43964342]
  [0.24075956 0.91900473 0.92152512 0.07889459 0.85709804]]

 [[0.41324946 0.0068249  0.69560568 0.39026436 0.32608486]
  [0.55747148 0.44194071 0.6534555  0.14342233 0.50988849]
  [0.24846021 0.64466818 0.882763   0.10865531 0.29621703]]]



### 4. Print a.


In [5]:
### [your code here]
print(a)

[[[7 8 0 9 6]
  [2 7 7 2 4]
  [8 1 5 5 5]]

 [[8 9 7 3 9]
  [5 3 6 4 5]
  [6 8 8 0 7]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
### [your code here]

# Create a 5x2x3 array filled with ones
b = np.ones((5, 2, 3), dtype= int)
print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [7]:
#---Method randint()---

# This also works because randint(1, 2) always returns 1
test_b = np.random.randint(1, 2, size=(5, 2, 3))
print(test_b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 6. Print b.


In [8]:
### [your code here]
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
### [your code here]

# Compare the total number of elements in both arrays
a.size == b.size

True


### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]

add_array = a + b

# ValueError: This operation will raise an error because the array shapes are different and not broadcast-compatible.

No, this will generates ValueError.
- ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
c = np.transpose(b)
c.shape

(3, 2, 5)

In [12]:
### [your code here]

# Transpose array b using a specific axis order
c = np.transpose(b, axes=(1, 2, 0))
c.shape

(2, 3, 5)

In [13]:
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


- A normal transpose does not give the required shape
- We use `transpose` with the `axes` argument to rearrange dimensions
- This converts `b` from `(5, 2, 3)` to `(2, 3, 5)`, matching `a`


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [14]:
# [your code here]

# Add arrays a and c
d = a + c

print(d)

[[[ 8  9  1 10  7]
  [ 3  8  8  3  5]
  [ 9  2  6  6  6]]

 [[ 9 10  8  4 10]
  [ 6  4  7  5  6]
  [ 7  9  9  1  8]]]


**Why does it work now?**

It works now because both arrays have the **same shape**.

* Array `a` has shape `(2, 3, 5)`
* Array `c` was transposed to also have shape `(2, 3, 5)`
* NumPy allows element-wise addition only when array shapes match


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [15]:
### [your code here]
print("a:\n", a)
print("d:\n", d)

a:
 [[[7 8 0 9 6]
  [2 7 7 2 4]
  [8 1 5 5 5]]

 [[8 9 7 3 9]
  [5 3 6 4 5]
  [6 8 8 0 7]]]
d:
 [[[ 8  9  1 10  7]
  [ 3  8  8  3  5]
  [ 9  2  6  6  6]]

 [[ 9 10  8  4 10]
  [ 6  4  7  5  6]
  [ 7  9  9  1  8]]]


Array `d` is obtained by adding array `a` and array `c`.

Since array `c` contains only ones, each element in `a` is increased by 1.

As a result, every element in array `d` is exactly **1 greater** than the corresponding element in array `a`.



### 12. Multiply a and c. Assign the result to e.


In [16]:
### [your code here]

# Multiply arrays a and c element-wise
e = a * c
print(e)

[[[7 8 0 9 6]
  [2 7 7 2 4]
  [8 1 5 5 5]]

 [[8 9 7 3 9]
  [5 3 6 4 5]
  [6 8 8 0 7]]]




### 13. Does e equal to a? Why or why not?


In [17]:
### [your code here]

print("a:\n", a)
print("e:\n", e)
e == a

a:
 [[[7 8 0 9 6]
  [2 7 7 2 4]
  [8 1 5 5 5]]

 [[8 9 7 3 9]
  [5 3 6 4 5]
  [6 8 8 0 7]]]
e:
 [[[7 8 0 9 6]
  [2 7 7 2 4]
  [8 1 5 5 5]]

 [[8 9 7 3 9]
  [5 3 6 4 5]
  [6 8 8 0 7]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

Yes, array `e` is equal to array `a`.

**Reason:**

* Array `e` is created by multiplying `a` with `c`
* Array `c` contains only ones
* Multiplying by 1 does not change the value

So, element by element, `e` and `a` are exactly the same.


**Why**
- Multiplying by a matrix/array of ones does not change the original values (identity behavior in element-wise multiplication).



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [18]:
### [your code here]

# Find the maximum value in array d
d_max = np.max(d)
print(f"Maximum value in d: {d_max}")

# Find the minimum value in array d
d_min = np.min(d)
print(f"Minimum value in d: {d_min}")

# Calculate the mean value of array d
d_mean = np.mean(d)
print(f"Mean value in d: {d_mean:.2f}")

Maximum value in d: 10
Minimum value in d: 1
Mean value in d: 6.47



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [19]:
### [your code here]

# Create an empty array with the same shape as d
f = np.empty(d.shape, dtype=int)
f.shape

(2, 3, 5)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [20]:
### [your code here]

# Assign labels to f based on values in d
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)

[[[ 75  75   0 100  75]
  [ 25  75  75  25  25]
  [ 75  25  25  25  25]]

 [[ 75 100  75  25 100]
  [ 25  25  75  25  25]
  [ 75  75  75   0  75]]]


In [21]:
#---Method Loops----

# Loop through all indices of d
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):

            value = d[i, j, k]

            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75
print(f)

[[[ 75  75   0 100  75]
  [ 25  75  75  25  25]
  [ 75  25  25  25  25]]

 [[ 75 100  75  25 100]
  [ 25  25  75  25  25]
  [ 75  75  75   0  75]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [22]:
### [your code here]

# Print d and f to verify the result
print("Array d:\n", d)
print("\nArray f:\n", f)

Array d:
 [[[ 8  9  1 10  7]
  [ 3  8  8  3  5]
  [ 9  2  6  6  6]]

 [[ 9 10  8  4 10]
  [ 6  4  7  5  6]
  [ 7  9  9  1  8]]]

Array f:
 [[[ 75  75   0 100  75]
  [ 25  75  75  25  25]
  [ 75  25  25  25  25]]

 [[ 75 100  75  25 100]
  [ 25  25  75  25  25]
  [ 75  75  75   0  75]]]


Yes, the result of `f` is as expected.

* Each value in `f` correctly corresponds to the value in `d` based on the defined rules
* Minimum values in `d` are labeled as `0` in `f`
* Maximum values in `d` are labeled as `100` in `f`
* Values between `d_min` and `d_mean` are labeled as `25`
* Values between `d_mean` and `d_max` are labeled as `75`.


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [23]:
### [your code here]
# Create an empty string array
g = np.empty((2, 3, 5), dtype=str)

# Assign string labels based on values in d
g[d == d_min] = "A"
g[(d > d_min) & (d < d_mean)] = "B"
g[d == d_mean] = "C"
g[(d > d_mean) & (d < d_max)] = "D"
g[d == d_max] = "E"

print(g)

[[['D' 'D' 'A' 'E' 'D']
  ['B' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'B']]

 [['D' 'E' 'D' 'B' 'E']
  ['B' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'A' 'D']]]


In [24]:
#---Method pyhton loops----
# Create an empty array of strings with the same shape as d
f_str = np.empty(d.shape, dtype=object)

# Loop through all elements
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):

            value = d[i, j, k]

            if value == d_min:
                f_str[i, j, k] = "A"
            elif value > d_min and value < d_mean:
                f_str[i, j, k] = "B"
            elif value == d_mean:
                f_str[i, j, k] = "C"
            elif value > d_mean and value < d_max:
                f_str[i, j, k] = "D"
            elif value == d_max:
                f_str[i, j, k] = "E"

# Print result
f_str

array([[['D', 'D', 'A', 'E', 'D'],
        ['B', 'D', 'D', 'B', 'B'],
        ['D', 'B', 'B', 'B', 'B']],

       [['D', 'E', 'D', 'B', 'E'],
        ['B', 'B', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'A', 'D']]], dtype=object)